# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('D', 'Django'), ('F', 'Facebook'), ('N', 'Naver')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
