# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
