# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170709_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birth_date',
        ),
    ]
