# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170715_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
