# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_delete_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
